kind: pipeline
name: testing deploy

steps:

  # - name: check ansible playbook syntax for deploy
  #   image: plugins/ansible
  #   environment:
  #   secrets: [ SSH_PRIVATE_KEY_STAGING ]
  #   settings:
  #     playbook: .ansible/playbook.yml
  #     inventory: .ansible/inventory
  #     private_key: $SSH_PRIVATE_KEY_STAGING
  #     syntax_check: true
  #   when:
  #     event:
  #     - dev

  - name: apply ansible playbook for deploy
    image: plugins/ansible
    environment:
      - host_ip2: 34.77.241.27
      - host_ip:
          from_secret: host_ip
    settings:
      playbook: .ansible/playbook.yml
      inventory: .ansible/inventory.yml
      private_key:
        from_secret: ansible_private_key
      # ssh_common_args: '-o StrictHostKeyChecking=no'
      verbose: 0
    when:
      branch:
      - master
      - dev

# ---
# kind: secret
# name: ansible_private_key
# data: SSH_PRIVATE_KEY_STAGING

# ---
# kind: secret
# data:
#   ansible_private_key: SSH_PRIVATE_KEY_STAGING


