kind: pipeline
name: testing deploy

steps:

  # - name: check ansible playbook syntax for deploy
  #   image: plugins/ansible
  #   environment:
  #   secrets: [ SSH_PRIVATE_KEY_STAGING ]
  #   settings:
  #     playbook: .ansible/playbook.yml
  #     inventory: .ansible/inventory
  #     private_key: $SSH_PRIVATE_KEY_STAGING
  #     syntax_check: true
  #   when:
  #     event:
  #     - dev

  - name: apply ansible playbook for deploy
    image: plugins/ansible
    # secrets: [ SSH_PRIVATE_KEY_STAGING ]
    secrets: [ ansible_private_key ]
    settings:
      playbook: .ansible/playbook.yml
      inventory: .ansible/inventory
      # private_key: $SSH_PRIVATE_KEY_STAGING
      private_key: $ansible_private_key
      # private_key:
        # from_secret: ansible_private_key
      # ssh_common_args: '-o StrictHostKeyChecking=no'
      verbose: 4
    # when:
    #   event:
    #   - dev

# ---
# kind: secret
# name: ansible_private_key
# data: SSH_PRIVATE_KEY_STAGING

# ---
# kind: secret
# data:
#   ansible_private_key: SSH_PRIVATE_KEY_STAGING


