version: '3.5'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    depends_on:
      - redis
    # ports:
    #   - "80:80"
    #   - "443:443"

  redis:
    container_name: redis-test
    image: redis:5.0
    restart: always
